theme: jekyll-theme-slate
lsi: false
safe: true
source: https://github.com/adminph-de/tf-azure-backend
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
